
language: python

python:
  - "3.7"

install:
  - pip install lxml
  - pip install semantic_version
  - pip install coverage
  - pip install coveralls
  - pip install scrutinizer-ocular

script:
  - coverage run alldoctest.py

after_success:
  - coveralls
  - ocular
