
language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

# command to install dependencies
install:
  - pip install lxml
  - pip install semantic_version
  - pip install coverage
  - pip install scrutinizer-ocular

# command to run tests
script:
  - ocular
